import type { Schema } from '../schema-dsl/ast.js';
import { getRouteMountEntries } from './route-generator.js';

export class AppGenerator {
  constructor(private readonly schema: Schema) {}

  generate(): string {
    const mounts = getRouteMountEntries(this.schema);
    const imports = mounts.map((entry) => `import ${entry.importName} from './routes/${entry.fileName.replace(/\.ts$/, '.js')}';`).join('\n');
    const routes = mounts.map((entry) => `  app.route('/${entry.basePath}', ${entry.importName});`).join('\n');

    return [
      '// Auto-generated by AppGenerator. Do not edit manually.',
      "import { pathToFileURL } from 'node:url';",
      "import { Pool } from 'pg';",
      "import { Hono } from 'hono';",
      "import { logger } from 'hono/logger';",
      "import { prettyJSON } from 'hono/pretty-json';",
      "import { serve } from '@hono/node-server';",
      imports,
      "import { createAuthMiddleware } from '../src/api/auth/middleware.js';",
      "import { createJwtResolver } from '../src/api/auth/jwt-resolver.js';",
      "import type { AuthResolver } from '../src/api/auth/types.js';",
      "import { createDbMiddleware } from '../src/api/middleware/db.js';",
      "import { handleError } from '../src/api/middleware/errors.js';",
      "import type { AppEnv } from '../src/api/types.js';",
      '',
      'export interface CreateAppOptions {',
      '  pool?: Pool;',
      '  authResolver?: AuthResolver;',
      '}',
      '',
      'export function createApp(options: CreateAppOptions = {}): Hono<AppEnv> {',
      '  const app = new Hono<AppEnv>();',
      '  app.use(logger());',
      '  app.use(prettyJSON());',
      '  app.use(createDbMiddleware({ pool: options.pool }));',
      '  app.use(createAuthMiddleware(options.authResolver ?? createJwtResolver()));',
      '  app.onError(handleError);',
      '',
      routes,
      '',
      '  return app;',
      '}',
      '',
      'const isMain = import.meta.url === pathToFileURL(process.argv[1] ?? \'\').href;',
      '',
      'if (isMain) {',
      '  const port = Number(process.env.PORT ?? 3000);',
      '  serve({ fetch: createApp().fetch, port }, () => {',
      '    console.log(`Server running at http://localhost:${port}`);',
      '  });',
      '}',
      '',
    ].join('\n');
  }
}

export function generateAppFile(schema: Schema): string {
  return new AppGenerator(schema).generate();
}
