import path from 'node:path';
import type { Schema } from '../schema-dsl/ast.js';
import { discoverCustomRoutes } from './custom-route-scanner.js';
import { getRouteMountEntries } from './route-generator.js';

export interface AppGeneratorOptions {
  customRoutesDir?: string;
}

const DEFAULT_CUSTOM_ROUTES_DIR = path.resolve('src/routes');

export class AppGenerator {
  constructor(
    private readonly schema: Schema,
    private readonly options: AppGeneratorOptions = {},
  ) {}

  generate(): string {
    const mounts = getRouteMountEntries(this.schema);
    const generatedImports = mounts
      .map((entry) => `import ${entry.importName} from './routes/${entry.fileName.replace(/\.ts$/, '.js')}';`)
      .join('\n');
    const generatedRoutes = mounts
      .map((entry) => `  app.route('/${entry.basePath}', ${entry.importName});`)
      .join('\n');

    const customRoutesDir = this.options.customRoutesDir ?? DEFAULT_CUSTOM_ROUTES_DIR;
    const customMounts = discoverCustomRoutes(customRoutesDir);
    const customImports = customMounts
      .map((entry) => `import ${entry.importName} from '${entry.importPath}';`)
      .join('\n');
    const customRoutes = customMounts
      .map((entry) => `  app.route('/${entry.basePath}', ${entry.importName});`)
      .join('\n');

    const routeImports = [generatedImports, customImports].filter(Boolean).join('\n');
    const routeMounts = [generatedRoutes, customRoutes].filter(Boolean).join('\n');

    return [
      '// Auto-generated by AppGenerator. Do not edit manually.',
      "import { pathToFileURL } from 'node:url';",
      "import { Pool } from 'pg';",
      "import { Hono } from 'hono';",
      "import { logger } from 'hono/logger';",
      "import { prettyJSON } from 'hono/pretty-json';",
      "import { serve } from '@hono/node-server';",
      routeImports,
      "import { createAuthMiddleware } from '../src/api/auth/middleware.js';",
      "import { createJwtResolver } from '../src/api/auth/jwt-resolver.js';",
      "import type { AuthResolver } from '../src/api/auth/types.js';",
      "import { createDbMiddleware } from '../src/api/middleware/db.js';",
      "import { handleError } from '../src/api/middleware/errors.js';",
      "import type { AppEnv } from '../src/api/types.js';",
      '',
      'export interface CreateAppOptions {',
      '  pool?: Pool;',
      '  authResolver?: AuthResolver;',
      '}',
      '',
      'export function createApp(options: CreateAppOptions = {}): Hono<AppEnv> {',
      '  const app = new Hono<AppEnv>();',
      '  app.use(logger());',
      '  app.use(prettyJSON());',
      '  app.use(createDbMiddleware({ pool: options.pool }));',
      '  app.use(createAuthMiddleware(options.authResolver ?? createJwtResolver()));',
      '  app.onError(handleError);',
      '',
      routeMounts,
      '',
      '  return app;',
      '}',
      '',
      'const isMain = import.meta.url === pathToFileURL(process.argv[1] ?? \'\').href;',
      '',
      'if (isMain) {',
      '  const port = Number(process.env.PORT ?? 3000);',
      '  serve({ fetch: createApp().fetch, port }, () => {',
      '    console.log(`Server running at http://localhost:${port}`);',
      '  });',
      '}',
      '',
    ].join('\n');
  }
}

export function generateAppFile(schema: Schema, options?: AppGeneratorOptions): string {
  return new AppGenerator(schema, options).generate();
}
